apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: greeter-client
  name: greeter-client
spec:
  replicas: 2
  selector:
    matchLabels:
      run: greeter-client
  template:
    metadata:
      labels:
        run: greeter-client
    spec:
      containers:
      - name: greeter-client
        image: felipeblassioli/demo-grpc-lb:0.0.5
        imagePullPolicy: Always
        args:
        - /bin/greeter_client_dns
        - greeter-server:8080